Support for setting incomingDir
QubesOS/qubes-core-agent-windows pull request #11
Opened 2024-01-25 13:43 UTC by fepitre

2024-01-26 14:30 UTC, marmarek requested changes
This leaks documentsPath now. It should be retrieved only when used for default incoming dir

2024-03-30 14:53 UTC, fepitre commented
@marmarek?

2024-03-31 07:42 UTC, marmarek commented
@omeg can you review? Is it okay to merge independently, or do you modify it too in your branch?

2024-03-31 10:13 UTC, omeg commented
I've made some changes in my branch but this can be merged as is. I'll incorporate it into my branch as well.

2024-04-01 17:00 UTC, omeg commented
Actually I have one question: if the incoming dir comes from the `FileCopy` RPC argument, how will it be filtered? Can the source VM write files anywhere? What are the defaults?

2024-04-02 07:40 UTC, fepitre commented
> Actually I have one question: if the incoming dir comes from the `FileCopy` RPC argument, how will it be filtered? Can the source VM write files anywhere? What are the defaults?

This is very similar to https://github.com/QubesOS/qubes-core-agent-linux/blob/main/qubes-rpc/qfile-unpacker.c#L60 and only the destination qube can manage where to unpack the incoming files. Typically, for the builder, it's a specific RPC inside the build qube (destination qube) that pass argument to this RPC and will follow it to unpacker. By default, this is not possible with `FileCopy` so in the default Qubes setup, it is not possible for a source qube to select destination path inside the destination qube.

2024-04-02 07:48 UTC, omeg commented
Alright, I thought so. All good then! 👍

2024-06-03 07:37 UTC, fepitre commented
@marmarek ping for this PR.

2025-11-12 11:38 UTC, omeg commented
Implemented in aaa0fbb8a6aba9e8aa84748a25901d5875dfeff6

2025-11-12 11:38 UTC, closed without merging